freebsd_instance:
  image: freebsd-12-0-release-amd64

main_task:
  script:
    - uname -a
    - yes | pkg install git gmake

    - ls
    - cc --version
    - c++ --version

    - git submodule init
    - git submodule update

    - gmake all
