freebsd_instance:
  image_family: freebsd-12-1

main_task:
  install_script:
    - uname -a
    - pkg install -y git gmake cmake

  script:
    - ls
    - cc --version
    - c++ --version

    - git submodule init
    - git submodule update

    - cmake -H. -B_build
    - cmake --build _build
    - cd _build
    - ctest -VV
