language: C
matrix:
  include:
    - name: "Basic linux gcc"
      os: linux
      sudo: false
      compiler: gcc
      env: CLANGFORMAT=ON
      addons:
        apt:
          packages:
          - clang-format

    - name: "Basic linux clang"
      os: linux
      compiler: clang


before_script:
  - git submodule init
  - git submodule update

script:
  - cmake -H. -B_build
  - cmake --build _build
  - cd _build
  - ctest -VV
  - cd ..
  - |
    if [ "${CLANGFORMAT}" = "ON" ]; then
      clang-format main.c > main_formatted.c
      diff main.c main_formatted.c
    fi


