language: C
matrix:
  include:
    - name: "Basic linux gcc"
      os: linux
      sudo: false
      compiler: gcc
      addons:
        apt:
          packages:
          - clang-format

before_script:
  - git submodule init
  - git submodule update

script:
  - cmake -H. -B_build
  - cmake --build _build
  - cd _build
  - ctest -VV
  - cd ..
  - clang-format --version


